const productsData = [
        {name:"Moter",
         price:999,
         description:"The fan motor DF6125 is a compact and reliable motor used for moving air in small cooling and ventilation systems. It is commonly installed in exhaust fans refrigerators air coolers and small air circulation units. This motor changes electrical energy into rotating motion which helps the fan blades spin smoothly and create steady airflow. The DF6125 fan motor is designed to use low electricity which helps it run for long hours without overheating. Its simple structure makes it durable and reduces the need for frequent maintenance. The motor provides stable rotation which helps reduce vibration and keeps the noise level low. Because of its strong performance and long life it is widely used in household appliances and small commercial machines. The DF6125 fan motor is a good choice for applications that require constant air movement with smooth operation and reliable output.",
         star:4,
         imgCount:7,
        img:"/img/prod/Moter (1).jpeg",
        },
        {name:"Fan moter (DF6125)",
         price:999,
         description:"A fan motor DF6125 is a compact electric motor designed to drive small cooling or ventilation fans in household and industrial appliances. It typically functions as an evaporator or blower fan motor, providing consistent airflow to circulate air, remove heat, or vent moisture in systems like refrigerators, ovens, air purifiers, or HVAC hoods. These motors are engineered for reliable performance with low noise output, stable starting torque, and long service life under continuous operation. Rated for a broad operating temperature range (often from below freezing to high heat), they offer durable insulation and minimal electrical noise, ensuring safe, efficient airflow in tight spaces. The DF6125 variant (similar to models like YJ6125) usually operates at standard mains voltages and moderate power levels (~30–35 W) with speeds near ~2900 RPM, making it suitable for compact fan assemblies where space, efficiency, and quiet operation are priorities.",
         star:5,
         imgCount:4,
        img:"/img/prod/Fan moter (DF6125) (1).jpeg",
        },
        {name:"Fan moter (TG160)",
         price:999,
         description:"The fan motor TG160 is a type of electric motor made to power fan blades and move air in different appliances It is often used in ceiling fans table fans air coolers and ventilation systems where air circulation is needed This motor takes electrical energy and converts it into mechanical motion causing the fan blades to turn and produce airflow The TG160 motor is designed to be strong and long lasting while using energy efficiently It runs smoothly with low vibration and low noise which makes it suitable for indoor use in homes offices and small shops The construction of this motor is simple yet reliable and it needs little maintenance It works well even when running for many hours at a time The TG160 fan motor provides steady performance and consistent airflow to keep spaces cooler and more comfortable It is a practical choice for many air moving applications",
         star:4,
         imgCount:4,
        img:"/img/prod/Fan moter (TG160) (1).jpeg",
        },
        {name:"Ac Axal fan",
         price:999,
         description:"An AC axial fan is a type of air moving device that uses alternating current to spin its blades in a straight airflow direction It is called axial because the air moves parallel to the fan shaft This kind of fan is widely used in cooling systems ventilation units machinery cabinets electronic devices and industrial equipment Its main purpose is to provide steady airflow and remove heat from enclosed spaces An AC axial fan is valued for its simple design strong performance and long operating life It can run for many hours without losing efficiency and it requires very little maintenance The fan produces good airflow while keeping noise at a moderate level which makes it suitable for both home and industrial use The blades and motor are designed to handle continuous operation and various temperature conditions Because of its reliability the AC axial fan is a preferred choice for cooling electronic panels compressors generators and similar equipment",
         star:4,
         imgCount:6,
        img:"/img/prod/Ac Axal fan (1).jpeg",
        },
        {name:"Fan Moter de fridge",
         price:999,
         description:"A fridge fan motor is a small electric motor used inside a refrigerator to keep air moving across the cooling coils and throughout the compartments It helps maintain even temperature so food stays fresh for a longer time The motor spins a small fan blade that circulates cold air from the evaporator section to the rest of the fridge This steady airflow prevents ice buildup and helps the cooling system work more efficiently The fridge fan motor is designed for continuous operation and can run for long hours without overheating It uses low power and makes very little noise which is important in home appliances The motor is usually compact durable and protected from moisture and dust so it can work reliably in cold conditions With proper airflow created by the fan motor the fridge cools faster stays stable and uses less energy Overall the fridge fan motor plays a key role in smooth and efficient refrigerator performance",
         star:4,
         imgCount:13,
        img:"/img/prod/Fan Moter de fridge (1).jpeg",
        },
        {name:"Pressure gauge car washer, service pump",
         price:999,
         description:"A pressure gauge for a car washer service pump is a measuring device that shows the amount of water pressure produced by the pump It helps the user check if the machine is working at the correct pressure level The gauge is usually connected near the outlet of the pump so it can display real time pressure while the washer is running This tool is important because too much pressure can damage parts while low pressure can reduce cleaning performance The pressure gauge helps the operator adjust the pump settings and maintain smooth operation It is designed to handle strong water flow and sudden changes in pressure The gauge has a clear readable scale which allows easy monitoring during car washing tasks It is built with durable materials so it can work in outdoor and workshop conditions With a reliable pressure gauge the car washer service pump performs better stays safe and delivers consistent cleaning results",
         star:5,
         imgCount:3,
        img:"/img/prod/Pressure gauge car washer, service pump (1).jpeg",
        },
        {name:"Car washer pump head(panther)",
         price:999,
         description:"A car washer pump head Panther is a strong and reliable part used in high pressure washing machines It is designed to control water flow and create the powerful pressure needed for cleaning cars bikes and other vehicles The pump head is the main section where water enters builds pressure and moves out through the hose for washing The Panther type pump head is known for its solid build smooth performance and long service life It can handle heavy duty use and continuous operation in workshops and car service stations The internal parts are made to resist wear and maintain steady pressure even during long cleaning sessions This pump head helps the washer deliver strong water output so dirt mud and stains can be removed easily It also ensures stable pressure which improves cleaning quality and reduces strain on the machine The Panther pump head is widely used because of its strong performance reliability and easy maintenance",
         star:4,
         imgCount:5,
        img:"/img/prod/Car washer pump head (panther) (3).jpeg",
        },
        {name:"Car washer pump head(sun top)",
         price:999,
         description:"A car washer pump head Sun Top is a durable and efficient part used in high pressure washing machines It is designed to control water flow and create the strong pressure needed for cleaning cars bikes and other vehicles The pump head is the main component where water is drawn in compressed and pushed out with high force The Sun Top pump head is known for its sturdy construction smooth operation and long working life It can handle regular use in car service centers workshops and home washing setups The internal parts are made to resist friction and maintain stable pressure for effective cleaning This pump head helps remove dust mud oil and tough dirt with powerful water output It also keeps the machine running safely by providing balanced and consistent pressure The Sun Top pump head is trusted for its strength reliability and low maintenance needs making it a practical choice for many car washing systems",
         star:5,
         imgCount:6,
        img:"/img/prod/Car washer pump head(sun top) (1).jpeg",
        },
        {name:"Manifold, gas mitter high pressure",
         price:999,
         description:"A manifold gas meter high pressure is a device used to measure and control the flow of gas in systems that operate with strong pressure It is commonly used in industrial plants gas supply lines welding stations and HVAC maintenance setups The manifold has multiple ports that allow gas to pass through different hoses so the user can monitor pressure from various sides The attached pressure meter shows accurate readings which helps maintain safe and stable operation The body of the manifold is made from strong material so it can handle high pressure without leaking or breaking This device helps technicians adjust gas flow check system performance and detect pressure changes before any problem occurs A high pressure manifold gas meter is important for safe handling of gas because it ensures proper control during filling testing or maintenance work It is reliable easy to use and designed for long lasting performance in tough working conditions",
         star:4,
         imgCount:5,
        img:"/img/prod/Manifold, gas mitter high pressure (1).jpeg",
        },
        {name:"Manyfold gas meter high pressure, 500 and 800PSI",
         price:999,
         description:"A manifold gas meter high pressure rated at 500 and 800 PSI is a device used to measure and control gas flow in systems that require strong pressure It is commonly used in industrial plants laboratories welding stations and gas supply lines The manifold has multiple ports that allow gas to pass through different hoses and provides readings from each connection The pressure meter shows accurate values so the operator can maintain safe and stable gas flow The high pressure rating of 500 and 800 PSI allows the device to handle demanding applications without leaks or failures The body is made from durable materials to withstand high pressure and long term use It helps technicians regulate gas flow monitor system performance and detect pressure fluctuations before problems occur This manifold gas meter is essential for safety reliability and effective operation in high pressure gas systems",
         star:5,
         imgCount:4,
        img:"/img/prod/Manyfold gas meter high pressure, 500 and 800PSI (3).jpeg",
        },
        {name:"250PSI gauge meter",
         price:999,
         description:"A 250 PSI gauge meter is a device used to measure pressure in systems that operate up to 250 pounds per square inch It is commonly used in air compressors hydraulic systems gas pipelines and industrial equipment The gauge provides accurate readings so operators can monitor and control the pressure safely This helps prevent overpressure situations that can damage equipment or cause accidents The 250 PSI gauge meter is built from durable materials to withstand high pressure and harsh working conditions Its dial is easy to read allowing quick and reliable pressure monitoring The meter can be installed in different systems using threaded connections and works reliably for long periods with minimal maintenance It is widely used in workshops construction sites and factories where precise pressure measurement is essential A 250 PSI gauge meter ensures safety efficiency and consistent performance in high pressure applications",
         star:4,
         imgCount:5,
        img:"/img/prod/250PSI gauge meter (1).jpeg",
        },
        {name:"500 psi gauge meter",
         price:999,
         description:"A 500 PSI gauge meter is a device used to measure pressure in systems that operate up to 500 pounds per square inch It is commonly used in air compressors hydraulic systems gas pipelines car washer pumps and industrial equipment The gauge provides accurate readings so operators can monitor and control the pressure safely This prevents overpressure conditions that could damage machines or create hazards The 500 PSI gauge meter is made from strong durable materials that can withstand high pressure and harsh working environments Its dial is clear and easy to read allowing quick pressure checks and reliable monitoring The meter can be connected to different systems using threaded fittings and works for long periods with minimal maintenance It is widely used in workshops service stations and factories where precise pressure measurement is required A 500 PSI gauge meter ensures safety efficiency and consistent system performance",
         star:5,
         imgCount:5,
        img:"/img/prod/500 psi gauge meter (1).jpeg",
        },
        {name:"R 600a  compressor oil",
         price:999,
         description:"R600a compressor oil is a specially formulated lubricant used in refrigeration compressors that run on R600a refrigerant It helps reduce friction between moving parts and ensures smooth and efficient operation of the compressor This oil is compatible with the materials used in R600a systems and does not react with the refrigerant or cause deposits inside the compressor The main function of R600a compressor oil is to provide lubrication cooling and protection to the compressor components which increases their lifespan and prevents wear and tear It is usually synthetic or mineral based depending on the compressor design and operating conditions The oil is clear and stable at high and low temperatures which allows reliable performance in domestic refrigerators freezers and small commercial cooling systems Using the correct R600a compressor oil ensures energy efficient operation stable cooling performance and long lasting reliability of the refrigeration system It is essential for maintenance and smooth functioning of the compressor",
         star:4,
         imgCount:4,
        img:"/img/prod/R 600a  compressor oil (1).jpeg",
        },
        {name:"Royal flame butane gas can paint percent extra",
         price:999,
         description:"Royal Flame butane gas can is a portable fuel container used for lighters stoves torches and other small appliances that require butane gas It is designed for safety convenience and easy refilling Some cans come with an extra paint percent label which indicates that the container has additional gas compared to standard size providing more usage time without changing the can This makes it economical and practical for frequent users The gas inside is refined and clean which ensures smooth flame performance and reduces clogging in lighters or burners The can is sealed to prevent leaks and maintain pressure The compact design makes it easy to store and carry It is widely used in households workshops camping and outdoor cooking activities Using Royal Flame butane gas can with extra content allows longer operation time and reliable flame for everyday tasks and professional use",
         star:5,
         imgCount:2,
        img:"/img/prod/Royal flame butane gas can paint percent extra (1).jpeg",
        },
        {name:"Vacuum pump oil",
         price:999,
         description:"Vacuum pump oil is a specially designed lubricant used in vacuum pumps to ensure smooth operation and efficient performance It fills the pump chamber creating a seal that allows the pump to generate and maintain vacuum pressure The oil also lubricates moving parts reduces friction and prevents wear and tear which extends the life of the pump High quality vacuum pump oil is free from acids and other contaminants to prevent corrosion and deposits inside the pump It is formulated to maintain stability under high temperature and low pressure conditions making it suitable for continuous operation The oil helps improve pump efficiency by reducing energy consumption and maintaining consistent vacuum levels It is widely used in laboratories industrial equipment refrigeration systems and manufacturing processes Using the correct vacuum pump oil is essential for reliable performance long service life and minimal maintenance of vacuum pumps",
         star:4,
         imgCount:2,
        img:"/img/prod/Vacuum pump oil (1).jpeg",
        },
        {name:"Brazing Hand torch",
         price:999,
         description:"A brazing hand torch is a portable tool used to heat metals for joining or soldering purposes It is commonly used in plumbing HVAC refrigeration and metalworking applications The torch produces a controlled flame by burning fuel such as propane butane or acetylene mixed with oxygen allowing precise heating of the metal surface The brazing hand torch is designed for safety and ease of use with a handle that provides good grip and control over the flame intensity It can reach high temperatures required to melt filler metals without melting the base metals This tool helps create strong leak proof joints in pipes metal sheets and other components It is lightweight durable and easy to carry making it suitable for both professional and home use Using a brazing hand torch increases efficiency accuracy and quality of metal joining tasks while reducing the time and effort required for heating operations",
         star:5,
         imgCount:4,
        img:"/img/prod/Brazing Hand torch (1).jpeg",
        },
        {name:"MT selender wall best quality",
         price:999,
         description:"An MT cylinder wall best quality is a precision engineered component used in engines to house the piston and allow smooth movement during combustion It is made from high grade materials to resist wear heat and corrosion which ensures long lasting performance The cylinder wall is carefully machined to maintain accurate dimensions and surface finish This reduces friction between the piston and the wall improving efficiency and preventing damage to the engine The best quality MT cylinder wall provides stable operation under high pressure and high temperature conditions It helps maintain proper compression and reduces the risk of oil leakage It is widely used in automotive engines motorcycles generators and industrial machinery Using a high quality MT cylinder wall ensures reliable engine performance longer service life and lower maintenance costs It is essential for engine efficiency durability and smooth operation in all types of internal combustion engines",
         star:4,
         imgCount:4,
        img:"/img/prod/MT selender wall best quality (1).jpeg",
        },
        {name:"Split AC PCB universal",
         price:999,
         description:"A split AC PCB universal is a control board used in split air conditioning systems to manage and regulate various functions of the unit It acts as the brain of the air conditioner controlling the compressor fan motor temperature sensors and other electrical components This universal PCB is compatible with multiple models of split AC units making it convenient for repairs and replacements The board receives signals from the remote control and temperature sensors and processes them to operate the AC efficiently It helps maintain stable temperature smooth operation and energy efficiency The universal PCB is designed to be durable reliable and resistant to voltage fluctuations It ensures proper timing of compressor and fan operations and protects the unit from electrical faults Using a split AC PCB universal allows technicians to replace malfunctioning boards quickly restore full functionality and improve the lifespan of the air conditioner",
         star:5,
         imgCount:3,
        img:"/img/prod/Split AC PCB universal (1).jpeg",
        },
        {name:"Universal AC control system PCB  split AC",
         price:999,
         description:"A universal AC control system PCB for split AC is an electronic circuit board that manages the operation of a split air conditioner It controls the compressor fan motor temperature sensors and other electrical components ensuring smooth and efficient functioning This universal PCB is compatible with multiple brands and models of split AC units making it ideal for repair and replacement purposes It receives signals from the remote control and temperature sensors and processes them to regulate cooling or heating cycles fan speed and other functions The PCB helps maintain energy efficiency stable temperature and reliable performance while protecting the unit from electrical faults It is designed for durability and resistance to voltage fluctuations Using a universal AC control system PCB allows technicians to quickly replace faulty boards restore full AC functionality and extend the lifespan of the air conditioning system It is essential for reliable and efficient operation of split AC units",
         star:4,
         imgCount:4,
        img:"/img/prod/Universal AC control system PCB  split AC (1).jpeg",
        },
        {name:"Universal AC control system PCB split  AC non inverter qd-U08C  modal",
         price:999,
         description:"The universal AC control system PCB QD U08C is a replacement control board designed for split air conditioners that are non inverter type This control PCB manages and regulates the main functions of the air conditioner including compressor operation fan speed temperature control and mode selection This universal board can work with many brands and models of split AC units making it a versatile and economical choice for repair and replacement tasks The QD U08C model supports auto restart after power failure sleep mode stable temperature control and automatic defrost functions It usually has three fan speed options and works with double temperature sensors to maintain accurate cooling performance The PCB is compatible with standard 220 240 volt AC power systems and comes with a remote control interface so the user can adjust settings easily Using this universal PCB helps restore full AC functionality reduce maintenance costs and extend the life of an older air conditioner The PCB is suitable for technicians and service professionals dealing with common AC control issues",
         star:5,
         imgCount:4,
        img:"/img/prod/Universal AC control system PCB split  AC non inverter qd-U08C  modal (1).jpeg",
        },
        {name:"Samsung Friz inverter singal dor PCB",
         price:999,
         description:"A Samsung fridge inverter signal door PCB is an electronic control board used in Samsung refrigerators especially those with inverter technology It is one of the main printed circuit boards that manages signals from different parts of the fridge including the door sensors and cooling system The board receives input from the door switch to know when the fridge door is open or closed and then sends this information to the main control board for proper operation This helps control interior lights fans and temperature regulation based on door status The inverter signal PCB also works with the inverter compressor control to adjust cooling efficiency and maintain stable temperature inside the fridge Modern Samsung fridge PCBs handle multiple sensor signals from temperature sensors door switches and other components to allow smooth coordinated operation of the appliance A functioning signal door PCB ensures the fridge runs efficiently with correct responses to door opening and closing events Some replacement PCBs are available as universal or specific part models for Samsung fridges",
         star:4,
         imgCount:4,
        img:"/img/prod/Samsung Friz inverter singal dor PCB (1).jpeg",
        },
        {name:"Lg  singal dor firz PCB card  inverter",
         price:999,
         description:"A signal door fridge PCB card for LG inverter refrigerators is an electronic control board that receives and processes signals from the fridge door sensor and other components It works with the main inverter control system to manage how the refrigerator responds when the door is opened or closed and to maintain proper cooling and energy efficiency The PCB interprets input from the door switch temperature sensors and user control panel and sends this data to the main control electronics This allows lights fans compressor and alarms to work correctly based on door position and cooling requirements The board is designed to be compatible with LG inverter fridge systems and to support reliable operation over time It helps the fridge maintain stable temperature reduce power consumption and protect the compressor and other parts from damage Using a quality LG fridge PCB card ensures accurate signal handling smooth operation and longer life for the appliance",
         star:5,
         imgCount:3,
        img:"/img/prod/Lg  singal dor firz PCB card  inverter (1).jpeg",
        },
        {name:"Split AC  indor PCB dc Moter jack. YY dc PCB",
         price:999,
         description:"The split AC indoor PCB DC motor jack YY DC PCB is an electronic control board used in split air conditioners to operate the indoor fan motor It controls the speed direction and timing of the DC fan motor for efficient airflow and cooling performance This PCB is designed for indoor units and communicates with sensors temperature controllers and the remote control to maintain desired room temperature The YY DC PCB is compatible with many models of split AC units making it useful for repairs and replacements It provides stable operation low noise and energy efficient performance while protecting the motor from electrical faults The board is durable and can handle voltage fluctuations common in household electricity It ensures smooth starting stopping and speed changes of the indoor fan motor Using a reliable indoor PCB helps restore full functionality of a split AC and improves cooling efficiency and appliance lifespan",
         star:4,
         imgCount:3,
        img:"/img/prod/Split AC  indor PCB dc Moter jack. YY dc PCB (1).jpeg"
        },


        {name:"Ifb company modal m24FB-610A (Microwave oven, spare part magnet on)",
         price:999,
         description:"The M24FB‑610A magnetron is a critical high-voltage component of IFB microwave ovens, responsible for generating the microwave energy that cooks and heats food. Operating at a standard frequency of 2450 MHz, it converts electrical energy from the oven’s transformer into microwave radiation, which excites water molecules in food to produce heat efficiently. This magnetron typically delivers 850–1000 W of microwave power and features a filament voltage of approximately 3.4 V and current around 10 A, ensuring reliable performance. Its robust design includes mounting holes for secure installation and air-cooling capability to maintain temperature stability during prolonged use. The M24FB‑610A is compatible with various IFB and other household microwave models, making it a commonly replaced part when an oven stops heating. Proper handling is essential, as the magnetron operates at lethal high voltages. When replaced correctly, it restores full cooking functionality while maintaining safety and efficiency in the microwave oven.",
         star:5,
         imgCount:5,
        img:"/img/prod/Ifb company modal m24FB-610A (1).jpeg",
        },
        {name:"Lg 2 m214",
         price:999,
         description:"The LG 2M214 magnetron is a high voltage microwave generator used in many LG microwave ovens as the main source of cooking energy. It converts electrical power from the oven’s high voltage transformer into microwave radiation at approximately 2450 MHz which penetrates food and excites water molecules to produce heat. This magnetron typically delivers around 850 to 900 watts of microwave output making it suitable for standard household cooking and reheating tasks. It is designed with an air cooled structure and strong internal magnets to ensure efficient heat dissipation and stable performance during repeated cooking cycles. The 2M214 features a compact flange mounted design which makes it a common replacement part across various LG countertop microwave models. Because it operates at high voltage it must be handled carefully and professional installation is recommended to ensure safety and proper function.",
         star:5,
         imgCount:4,
        img:"/img/prod/Lg 2 m214 (1).jpeg",
        },
        {name:"Samsung om 75s(31)esgn",
         price:999,
         description:"The Samsung OM75S(31)ESGN is an original microwave magnetron assembly used in many Samsung household microwave oven models. It is the key component that generates microwave energy, converting high‑voltage electrical power from the oven’s transformer into microwaves at about 2450 MHz frequency, which heats and cooks the food inside the oven cavity. This magnetron is designed to provide roughly 850 W of microwave output, making it suitable for standard cooking, reheating, and defrosting tasks in everyday kitchen use.Constructed to Samsung’s specifications, the OM75S(31)ESGN features a robust metal housing and mounting points for secure installation. It helps ensure consistent performance and reliable heating over the life of the appliance. Because it operates at very high voltages and currents, replacing or servicing it should only be done by a trained technician with proper safety precautions to avoid electric shock or injury.",
         star:5,
         imgCount:6,
        img:"/img/prod/Samsung om 75s(31)esgn (1).jpeg",
        },
        {name:"Daikin 2 tan cassette AC PCB indor non inverter",
         price:999,
         description:"demo",
         star:5,
         imgCount:6,
        img:"/img/prod/Daikin 2 tan cassette AC PCB indor non inverter (1).jpeg",
        },
        {name:"Ex130035-7(H) modal part code non inverter  PCB Indore  Daikin split AC",
         price:999,
         description:"The Ex130035-7(H) is a model part code for the non-inverter PCB used in Daikin split ACs. Located in Indore, this part plays a crucial role in controlling and regulating the functioning of the air conditioner. It helps manage various electrical components, ensuring that the AC operates efficiently. The non-inverter PCB is designed for specific Daikin models, making it a key replacement part when the system stops functioning as expected. Proper installation is essential for maintaining optimal performance.",
         star:5,
         imgCount:6,
        img:"/img/prod/Ex130035-7(H) modal part code non inverter  PCB Indore  Daikin split AC (1).jpeg",
        },
        {name:"EX13025-48(E) modal part code part code. Outdoor unit PCB inverter 1.5 tan And 2 tan   Split AC Daikin",
         price:999,
         description:"The EX13025-48(E) is a model part code for the outdoor unit PCB used in Daikin 1.5 ton and 2 ton inverter split ACs. This PCB is responsible for controlling the outdoor unit’s electrical components, ensuring efficient cooling and heating performance. It regulates the communication between the indoor and outdoor units and helps in managing the inverter system, which adjusts the compressor speed for energy efficiency. When replaced, this part ensures the AC operates optimally.",
         star:5,
         imgCount:6,
        img:"/img/prod/EX13025-48(E) modal part code part code. Outdoor unit PCB inverter 1.5 tan And 2 tan   Split AC Daikin (1).jpeg",
        },
        {name:"EX22041 modal part code Daikin splits AC AC indor PCB card inverter AC  1 tan and 1.5 tan and 2 tan",
         price:999,
         description:"The EX22041 is a model part code for the indoor PCB card used in Daikin inverter split ACs of 1 ton, 1.5 ton, and 2 ton capacities. This PCB card controls and regulates the functioning of the indoor unit, managing the compressor, fan speed, and other components for efficient cooling or heating. It helps ensure smooth communication between the indoor and outdoor units, especially in inverter models, for optimized energy consumption and consistent performance. Proper installation of this part is essential for the AC’s overall functionality.",
         star:5,
         imgCount:6,
        img:"/img/prod/EX22041 modal part code Daikin splits AC AC indor PCB card inverter AC  1 tan and 1.5 tan and 2 tan (1).jpeg",
        },
        {name:"EC12063 modal parts code Daikin  outdoor  electric  expensan valve PCB coils inverter",
         price:999,
         description:"The EC12063 is a model part code for the outdoor electric expansion valve PCB used in Daikin inverter ACs. This part plays a crucial role in regulating the refrigerant flow in the outdoor unit by controlling the expansion valve, which adjusts the cooling capacity based on the temperature and pressure. It works in tandem with the inverter system to maintain efficient energy use while ensuring optimal performance of the air conditioner. The PCB also monitors the coils for any issues, ensuring smooth operation and energy efficiency.",
         star:5,
         imgCount:6,
        img:"/img/prod/EC12063 modal parts code Daikin  outdoor  electric  expensan valve PCB coils inverter (1).jpeg",
        },
        {name:"S2543579 parts code. Daikin AC inverter AC Remote  power hill",
         price:999,
         description:"The S2543579 is a part code for the Daikin inverter AC remote control. This remote is used to control various functions of the Daikin inverter air conditioner, including power on/off, temperature settings, fan speed, and mode adjustments. It ensures user-friendly operation, allowing you to adjust your AC's settings conveniently from a distance. The power hill feature on the remote may refer to specific energy-saving or performance modes designed to optimize power consumption and enhance cooling efficiency.",
         star:5,
         imgCount:6,
        img:"/img/prod/S2543579 parts code. Daikin AC inverter AC Remote  power hill (1).jpeg",
        },
        {name:"Ex624 part code Daikin display indor inverter AC  1.5 tan and 2 tan",
         price:999,
         description:"The EX624 is a part code for the indoor display unit used in Daikin inverter ACs with 1.5 ton and 2 ton capacities. This display unit shows important information such as the current temperature, mode, and operating status of the air conditioner. It allows users to easily monitor and control the AC settings. The EX624 is designed to work seamlessly with Daikin inverter models, providing clear and accurate readouts for efficient operation and user convenience.",
         star:5,
         imgCount:6,
        img:"/img/prod/Ex624 part code Daikin display indor inverter AC  1.5 tan and 2 tan (1).jpeg",
        },
        {name:"Ec 50 wid A20 R 22 5KW. parts code Daikin AC  non inverter AC split indoor PCB 50WIDA20A R4(5KW)",
         price:999,
         description:"The EC50 WID A20 R22 5KW is a part code for the non-inverter split AC indoor PCB used in Daikin ACs. This PCB controls the various functions of the indoor unit, ensuring efficient cooling and performance. It is compatible with R22 refrigerant and is designed to handle a 5KW power capacity. The model 50WIDA20A R4(5KW) is specifically used in non-inverter AC systems, providing stable operation and optimized energy use.",
         star:5,
         imgCount:6,
        img:"/img/prod/Ec 50 wid A20 R 22 5KW. parts code Daikin AC  non inverter AC split indoor PCB (1).jpeg",
        },
        {name:"EX13035-2(c) model part code Daikin split AC non inverter.  1.5 tan. Old modal",
         price:999,
         description:"The EX13035-2(C) is a part code for a non-inverter split AC model used in Daikin 1.5 ton units. This part is typically associated with older models of Daikin’s non-inverter split ACs. It plays a crucial role in controlling the electrical functions of the indoor or outdoor unit, ensuring efficient cooling performance. As an older model part, it may need to be replaced if the system is malfunctioning or if the AC stops functioning properly.",
         star:5,
         imgCount:6,
        img:"/img/prod/EX13035-2(c) model part code Daikin split AC non inverter.  1.5 tan. Old modal (1).jpeg",
        },
        {name:"Whirlpool fridge, PCB inverter model single door",
         price:999,
         description:"The PCB inverter in a Whirlpool single-door fridge is an essential part that controls the cooling system's operation. This inverter PCB manages the compressor's speed, optimizing energy consumption and ensuring that the fridge operates efficiently. It helps maintain the ideal temperature inside the fridge while reducing power usage, making the unit more energy-efficient. The inverter technology also enables smoother and quieter operation, providing better cooling performance compared to traditional systems.",
         star:5,
         imgCount:6,
        img:"/img/prod/Whirlpool fridge, PCB inverter model single door (1).jpeg",
        },
        {name:"Daikin remote, Cassata Ac",
         price:999,
         description:"The PCB inverter in a Whirlpool single-door fridge is an essential part that controls the cooling system's operation. This inverter PCB manages the compressor's speed, optimizing energy consumption and ensuring that the fridge operates efficiently. It helps maintain the ideal temperature inside the fridge while reducing power usage, making the unit more energy-efficient. The inverter technology also enables smoother and quieter operation, providing better cooling performance compared to traditional systems.",
         star:5,
         imgCount:6,
        img:"/img/prod/Daikin remote, Cassata Ac (1).jpeg",
        },
        {name:"Daikin split and cassette AC remote",
         price:999,
         description:"The Daikin split and cassette AC remote is designed to control the key functions of both split and cassette air conditioning units from Daikin. The remote allows users to adjust temperature, fan speed, cooling modes, and the on/off function of the AC. It typically includes features such as timer settings, sleep mode, and energy-saving options. With these features, users can optimize their comfort and energy consumption. The remote offers easy, convenient control, ensuring smooth operation of both split and cassette AC systems.",
         star:5,
         imgCount:6,
        img:"/img/prod/Daikin split and cassette AC remote (1).jpeg",
        },
        {name:"Daikin non-inverter split AC remote",
         price:999,
         description:"The Daikin non-inverter split AC remote is used to control the key functions of Daikin’s non-inverter split air conditioners. This remote allows users to easily adjust the temperature, fan speed, and cooling modes, as well as power the AC on or off. It typically features additional options like timer settings, sleep mode, and energy-saving functions to improve the overall user experience. Designed for convenience, this remote ensures smooth and easy operation of the AC from a distance.",
         star:5,
         imgCount:6,
        img:"/img/prod/Daikin non-inverter split AC remote (1).jpeg",
        },
        {name:"Wasing machine palseter Voltas beko",
         price:999,
         description:"The Voltas Beko washing machine is designed to provide efficient and reliable washing performance for everyday laundry needs. Known for its innovative features, it offers multiple wash programs for different fabric types and cleaning requirements. Voltas Beko machines are equipped with advanced technology that ensures energy-efficient operation while maintaining high-quality cleaning. The palseter feature (if referring to a specific model or function) may involve specialized washing cycles or energy-saving modes that help optimize performance and reduce power consumption.",
         star:5,
         imgCount:6,
        img:"/img/prod/Wasing machine palseter Voltas beko (1).jpeg",
        },
        {name:"Washing machine Onida and godrej palseter",
         price:999,
         description:"Onida aur Godrej washing machines dono hi apne palseter (agar yeh kisi specific model ya function ko refer kar raha ho) features ke liye jaana jaate hain. Ye washing machines apne advanced wash cycles aur energy efficiency ke liye mashhoor hain. Dono brands me multiple wash programs hote hain, jo alag-alag kapdon aur cleaning needs ke liye designed hote hain. Onida washing machines mein smart technology aur quick wash options hoti hain, jabki Godrej machines eco-friendly aur energy-saving features offer karti hain, jo electricity aur water consumption ko kam karte hain.",
         star:5,
         imgCount:6,
        img:"/img/prod/Washing machine Onida and godrej palseter (1).jpeg",
        },
        {name:"Godrej Wasing machine farantload palseter",
         price:999,
         description:"The Godrej front-load washing machine with palseter (agar yeh kisi specific feature ya function ko refer karta ho) is designed to provide superior washing performance and efficiency. Front-load washing machines from Godrej are known for their gentle fabric care and water-efficient technology. They typically offer a variety of wash programs for different fabrics, ensuring optimal cleaning while minimizing wear and tear on clothes. The palseter feature could refer to an energy-saving mode or a specific wash cycle designed to enhance washing performance while reducing power consumption.",
         star:5,
         imgCount:6,
        img:"/img/prod/Godrej Wasing machine farantload palseter (1).jpeg",
        },
        {name:"Spin drum Samsung 8 kg original",
         price:999,
         description:"The Samsung 8 kg spin drum is a key component in Samsung washing machines, designed for efficient spinning and water extraction during the wash cycle. This original spin drum ensures that clothes are cleaned thoroughly and efficiently while maintaining the integrity of fabrics. With a capacity of 8 kg, it is ideal for medium-sized households. The drum operates at high speeds to remove excess water from clothes, reducing drying time. Samsung's original spin drum is durable and built for long-lasting performance, ensuring smooth operation of the washing machine.",
         star:5,
         imgCount:6,
        img:"/img/prod/Spin drum Samsung 8 kg original (1).jpeg",
        },
        {name:"Multiple spin drum 7 kg",
         price:999,
         description:"The 7 kg multiple spin drum is designed for use in washing machines, typically offering multiple spin cycles for more efficient water extraction and faster drying. With a 7 kg capacity, it is ideal for smaller to medium-sized loads. This drum helps in achieving a better wash quality by evenly distributing clothes during the spin cycle, reducing fabric damage while ensuring effective water removal. Multiple spin options allow for customizing the spin speed and intensity depending on the fabric type and load size.",
         star:5,
         imgCount:6,
        img:"/img/prod/Multiple spin drum 7 kg (1).jpeg",
        },
        {name:"Multiple spin drum 6 kg",
         price:999,
         description:"The 6 kg multiple spin drum is designed for use in washing machines with a 6 kg capacity, ideal for smaller households or lighter laundry loads. This spin drum offers multiple spin cycle options, allowing users to select the appropriate spin speed based on fabric type and laundry load. The multiple spin features ensure that clothes are thoroughly wrung out, reducing drying time and minimizing moisture retention. The drum ensures even distribution of clothes during spinning, leading to effective water extraction while protecting fabrics from damage.",
         star:5,
         imgCount:6,
        img:"/img/prod/Multiple spin drum 6 kg (1).jpeg",
        },
        {name:"Videocon spin drum  m 6800",
         price:999,
         description:"The Videocon Spin Drum M 6800 is a key component in Videocon washing machines, designed for efficient washing and spinning. This spin drum is ideal for handling laundry loads, typically in medium-capacity models, and is known for its durability and reliable performance. The M 6800 model ensures that clothes are evenly spun, removing excess water effectively to reduce drying time. The design of the drum helps maintain fabric care while providing a powerful spin for better cleaning efficiency.",
         star:5,
         imgCount:6,
        img:"/img/prod/Videocon spin drum  m 6800 (1).jpeg",
        },
        {name:"Lg 6.5 kg spin drum",
         price:999,
         description:"The LG 6.5 kg spin drum is a crucial component in LG washing machines designed for efficient water extraction during the spin cycle. With a 6.5 kg capacity, it is ideal for smaller to medium-sized households. The spin drum ensures that clothes are evenly distributed during the spin cycle, which helps in effective water removal and reduces drying time. LG's spin drum technology is built for durability and smooth operation, providing gentle care for clothes while maintaining high efficiency in washing.",
         star:5,
         imgCount:6,
        img:"/img/prod/Lg 6.5 kg spin drum (1).jpeg",
        },
        {name:"Lg 7.5 kg spin drum  original",
         price:999,
         description:"The LG 7.5 kg spin drum (original) is a high-quality component designed for use in LG washing machines with a 7.5 kg capacity. This original spin drum ensures efficient washing and water extraction during the spin cycle. It provides powerful and consistent performance, helping to remove excess water from clothes, which reduces drying time. The drum’s design is built for durability, offering smooth and reliable operation while maintaining the integrity of fabrics. Ideal for medium to large-sized households, this drum is designed to handle moderate laundry loads with ease.",
         star:5,
         imgCount:6,
        img:"/img/prod/Lg 7.5 kg spin drum  original (1).jpeg",
        },
        {name:"Voltas beko spin drum 14 kg",
         price:999,
         description:"The Voltas Beko 14 kg spin drum is designed for use in Voltas Beko washing machines with a large capacity of 14 kg, making it suitable for larger households or heavier laundry loads. This spin drum is built to handle big loads efficiently, ensuring thorough water extraction during the spin cycle. It helps reduce drying time by removing excess water from clothes effectively. The drum’s design is durable and optimized for smooth operation, providing reliable performance while maintaining fabric care.",
         star:5,
         imgCount:6,
        img:"/img/prod/Voltas beko spin drum 14 kg (1).jpeg",
        },
        {name:"Samsung semi automatic washing machines pulsator chok saft",
         price:999,
         description:"The Samsung semi-automatic washing machine with a pulsator is designed to provide efficient washing for everyday laundry needs. The pulsator system uses a rotating disk to create a powerful washing motion, which helps in thoroughly cleaning clothes while reducing wear and tear. The chok saft feature (if referring to a specific mode or design element) could be related to improved water flow or energy-saving functions to enhance washing efficiency. Samsung's semi-automatic machines offer flexibility with separate wash and spin tubs, allowing you to control wash time and water levels for various types of clothes.",
         star:5,
         imgCount:6,
        img:"/img/prod/Samsung semi automatic washing machines pulsator chok saft (1).jpeg",
        },
        {name:"Samsung top load washing machine pulsator gol girai saft soft",
         price:999,
         description:"The Samsung top-load washing machine with a pulsator and gol girai saft soft (possibly referring to a gentle, soft washing motion) is designed to provide efficient and delicate washing for clothes. The pulsator mechanism in Samsung's top-load machines creates a powerful but gentle rotating action that ensures thorough cleaning while protecting fabrics from damage. The soft motion ensures that even delicate fabrics are treated carefully, preventing wear and tear during the wash. This type of system helps in maintaining the quality of clothes while delivering effective cleaning results.",
         star:5,
         imgCount:6,
        img:"/img/prod/Samsung top load washing machine pulsator gol girai saft soft (1).jpeg",
        },
        {name:"Voltas Biko 7 KG washing machine, pulsator small",
         price:999,
         description:"The Voltas Beko 7 KG washing machine with a small pulsator is designed to efficiently clean clothes with a compact yet powerful pulsator mechanism. The small pulsator helps in creating strong water flow to scrub clothes thoroughly, even with a 7 kg load capacity. Despite its smaller size, the pulsator ensures that clothes are washed effectively while reducing wear and tear on fabrics. This makes it an ideal option for",
         star:5,
         imgCount:6,
        img:"/img/prod/Voltas Biko 7 KG washing machine, pulsator small (1).jpeg",
        },
        {name:"Split AC LG NON INVERTER BOLWR MOTER. LONG SAFT AC 220-240V AC   Original",
         price:999,
         description:"The LG non-inverter split AC blower motor (with 220-240V AC power) is an original part designed for LG's non-inverter split air conditioners. This motor plays a crucial role in driving the blower fan, which circulates cool air throughout the room. The long saft (shaft) design ensures smooth and efficient operation, allowing the motor to run quietly while maintaining optimal airflow. With a voltage rating of 220-240V AC, this motor ensures reliable performance and consistent cooling. Being an original LG part, it guarantees high durability and compatibility with LG AC systems.",
         star:5,
         imgCount:6,
        img:"/img/prod/Split AC LG NON INVERTER BOLWR MOTER. LONG SAFT AC 220-240V AC   Original (1).jpeg",
        },
        {name:"Daikin blower motor split AC inverter DC voltage 310 v DC",
         price:999,
         description:"The Daikin blower motor for split inverter ACs operates on 310V DC voltage. This motor is responsible for driving the fan that circulates air throughout the room, providing effective cooling. The DC motor technology is known for its energy efficiency, as it adjusts its speed according to the cooling needs, offering quieter and smoother operation compared to traditional AC motors. It ensures reliable performance, optimized airflow, and improved durability, making it an essential component for Daikin inverter split ACs.",
         star:5,
         imgCount:6,
        img:"/img/prod/Daikin blower motor split AC inverter DC voltage 310 v DC (1).jpeg",
        },
        {name:"Samsung’ split AC blower moter PICL ORIGINAL  LONG SAFT 310 v DC  35 watt",
         price:999,
         description:"The Samsung split AC blower motor with PICL (likely referring to the motor type or brand) is an original component designed for Samsung split air conditioners. This motor operates on 310V DC voltage and consumes 35 watts of power. The motor drives the blower fan, ensuring efficient airflow for effective cooling. The long saft (shaft) design ensures smooth, stable rotation, minimizing noise and vibration. As an original Samsung part, it guarantees high performance, energy efficiency, and compatibility with Samsung's split AC systems.",
         star:5,
         imgCount:6,
        img:"/img/prod/Samsung’ split AC blower moter PICL ORIGINAL  LONG SAFT 310 v DC  35 watt (1).jpeg",
        },
        {name:"Long saft dc moter  lg and Samsung",
         price:999,
         description:"The long shaft DC motors used in LG and Samsung air conditioners are designed for efficient and reliable operation in split AC systems. These motors drive the blower fan, which circulates cool air throughout the room. The long shaft design ensures smooth and stable functioning, reducing vibrations and noise during operation. DC motors are energy-efficient and provide more precise control over the fan speed compared to traditional AC motors. Both LG and Samsung use these motors in their high-performance models to ensure quieter operation and improved durability.",
         star:5,
         imgCount:6,
        img:"/img/prod/Long saft dc moter  lg and Samsung (1).jpeg",
        },
        {name:"Daikin split ac Blower motor 310 DC volt 15 watt. Big jig",
         price:999,
         description:"The Daikin split AC blower motor operates on 310V DC voltage and consumes 15 watts of power. This motor is responsible for driving the blower fan, which circulates cool air throughout the room. The big jig could be referring to a larger, more powerful design or a specific type of motor used in certain Daikin models for enhanced airflow. The DC motor technology ensures energy efficiency and quieter operation compared to traditional AC motors, providing reliable and smooth performance for the air conditioner.",
         star:5,
         imgCount:6,
        img:"/img/prod/Daikin split ac Blower motor 310 DC volt 15 watt. Big jig (1).jpeg",
        },
        {name:"Lg spit AC blower moter AC volt 220-240 v. 15 watt long saft",
         price:999,
         description:"The LG split AC blower motor operates on an AC voltage range of 220-240V and consumes 15 watts of power. This motor is designed to drive the blower fan, which circulates cool air throughout the room. The long shaft design ensures smooth and stable operation, minimizing vibrations and noise. With energy-efficient 15W power consumption, it provides reliable and quiet performance, maintaining optimal airflow for effective cooling in the room.",
         star:5,
         imgCount:6,
        img:"/img/prod/Lg spit AC blower moter AC volt 220-240 v. 15 watt long saft (1).jpeg",
        },
        {name:"Carrier split ac blower moter. AC volt 220-240",
         price:999,
         description:"The Carrier split AC blower motor operates on an AC voltage range of 220-240V. This motor is designed to drive the blower fan, ensuring proper airflow and cooling efficiency in the room. With its energy-efficient design, it provides smooth and reliable performance while minimizing noise and vibrations. The motor plays a crucial role in maintaining the AC’s cooling performance by ensuring that air circulates effectively throughout the space.",
         star:5,
         imgCount:6,
        img:"/img/prod/Carrier split ac blower moter. AC volt 220-240 (1).jpeg",
        },
        {name:"Carrier AC split blower motor 220-240 volt AC. 30 watt",
         price:999,
         description:"The Carrier split AC blower motor operates on an AC voltage of 220-240V and consumes 30 watts of power. This motor drives the blower fan to circulate cool air throughout the room. The 30W power consumption ensures a balance between energy efficiency and effective airflow. Designed for smooth and stable operation, it helps maintain consistent cooling performance while minimizing noise and vibrations, making it an essential component for optimal air conditioning performance.",
         star:5,
         imgCount:6,
        img:"/img/prod/Carrier AC split blower motor 220-240 volt AC. 30 watt (1).jpeg",
        }, 
        {name:"Dc moter split ac blower 310 volt AC. 30 watt",
         price:999,
         description:"The DC motor split AC blower operates on 310V AC voltage and consumes 30 watts of power. This motor is responsible for driving the blower fan, circulating cool air efficiently throughout the room. The DC motor technology provides energy efficiency and smoother operation compared to traditional AC motors. With a 30W power consumption, it ensures effective airflow while minimizing noise and vibrations, leading to better performance and quieter cooling in split AC systems.",
         star:5,
         imgCount:6,
        img:"/img/prod/Dc moter split ac blower 310 volt AC. 30 watt (1).jpeg",
        },
        {name:"Lg split AC non invter  PCB card.  1.5 tan",
         price:999,
         description:"The LG split AC non-inverter PCB card for 1.5 ton units is an essential component that controls the various functions of the air conditioner. It manages electrical circuits, regulates the compressor, and ensures smooth communication between the indoor and outdoor units. This PCB card is designed for non-inverter models, helping maintain efficient cooling performance while ensuring safety and reliability. It plays a key role in the overall operation of the AC system, ensuring all settings are accurately controlled.",
         star:5,
         imgCount:6,
        img:"/img/prod/Lg split AC non invter  PCB card.  1.5 tan (1).jpeg",
        },
        {name:"Lg non inverter display PCB 6 wayare",
         price:999,
         description:"The LG non-inverter display PCB with 6-way connectors is responsible for controlling the display panel and managing the settings of the air conditioner. It connects various components, enabling the AC to show the correct information on the display, such as temperature, modes, and error codes. This PCB helps maintain efficient communication between the control panel and other electrical parts of the AC. The 6-way connectors ensure proper connectivity, ensuring reliable operation of the display system.",
         star:5,
         imgCount:6,
        img:"/img/prod/Lg non inverter display PCB 6 wayare (1).jpeg",
        },
        {name:"Videocon  ac PCB card  old modal",
         price:999,
         description:"The Videocon AC PCB card for old models is a crucial component that controls the internal operations of the air conditioner. It manages the electrical circuits, compressor functions, and communication between the indoor and outdoor units. In older models, the PCB card helps regulate temperature, fan speed, and cooling modes. If the AC stops working properly, the PCB card is often one of the first components to be checked or replaced, as it ensures all systems are functioning smoothly.",
         star:5,
         imgCount:6,
        img:"/img/prod/Videocon  ac PCB card  old modal (1).jpeg",
        },
        {name:"Lg split AC siwing moter  5 wayare",
         price:999,
         description:"The LG split AC swinging motor with 5-way connectors is responsible for controlling the horizontal or vertical movement of the air distribution louvers (flaps). This motor ensures that air is evenly distributed throughout the room by moving the louvers in a swinging motion. The 5-way connectors provide stable and efficient electrical connections to the motor, allowing it to function smoothly. Proper operation of this motor ensures better airflow and enhanced cooling performance in your LG split AC.",
         star:5,
         imgCount:6,
        img:"/img/prod/Lg split AC siwing moter  5 wayare (1).jpeg",
        },
        {name:"Subzero PCB  chiller  model 7510sz",
         price:999,
         description:"The Subzero PCB chiller model 7510SZ is an essential part of the Subzero chiller system. This PCB (Printed Circuit Board) controls the electrical functions and manages the operation of the chiller unit, regulating factors like temperature, compressor function, and safety mechanisms. The 7510SZ model is designed to ensure the chiller runs efficiently, providing reliable cooling performance. It helps in maintaining optimal temperatures for the cooling process, making it an important component for keeping the chiller system functioning smoothly.",
         star:5,
         imgCount:6,
        img:"/img/prod/Subzero PCB  chiller  model 7510sz (1).jpeg",
        },
        {name:"Daikin display 10 wayare big jack",
         price:999,
         description:"The Daikin display PCB with 10-way connectors (also referred to as a big jack) is responsible for managing the display functions in Daikin air conditioners. It controls the display panel that shows key information such as temperature, modes, fan speed, and error codes. The 10-way connectors ensure secure and stable electrical connections between the PCB and other parts of the AC system, enabling smooth operation. The big jack design ensures that the connectors are robust, offering long-lasting performance and reliability.",
         star:5,
         imgCount:6,
        img:"/img/prod/Daikin display 10 wayare big jack (1).jpeg",
        },
        {name:"Daikin split AC display  9 wayare model EX16022-1(A)",
         price:999,
         description:"The Daikin split AC display with 9-way connectors, model EX16022-1(A), is an important component that controls the display panel of the air conditioner. This display PCB manages the visualization of key information such as temperature settings, operating modes, fan speed, and error codes. The 9-way connectors ensure secure and efficient electrical connections between the PCB and the rest of the AC system, allowing seamless operation. The EX16022-1(A) model is designed for specific Daikin split AC units, ensuring compatibility and reliable performance.",
         star:5,
         imgCount:6,
        img:"/img/prod/Daikin split AC display  9 wayare model EX16022-1(A) (1).jpeg",
        },
        {name:"Voltas  dispenser hitter tank  original",
         price:999,
         description:"The Voltas dispenser heater tank (original) is a key component used in Voltas water dispensers, responsible for heating water to the desired temperature. This original tank ensures efficient heating and is designed to be durable and reliable for long-term use. It helps maintain a consistent water temperature, making it ideal for dispensing hot water when needed. The original part guarantees compatibility with Voltas dispensers, ensuring optimal performance and safety.",
         star:5,
         imgCount:6,
        img:"/img/prod/Voltas  dispenser hitter tank  original (2).jpeg",
        },
        // {name:"Samsung",
        //  price:999,
        //  description:"demo",
        //  star:5,
        //  imgCount:6,
        // img:"/img/prod/Samsung om 75s(31)esgn (1).jpeg",
        // },
        // {name:"Samsung",
        //  price:999,
        //  description:"demo",
        //  star:5,
        //  imgCount:6,
        // img:"/img/prod/Samsung om 75s(31)esgn (1).jpeg",
        // },
        // {name:"Samsung",
        //  price:999,
        //  description:"demo",
        //  star:5,
        //  imgCount:6,
        // img:"/img/prod/Samsung om 75s(31)esgn (1).jpeg",
        // },
        // {name:"Samsung",
        //  price:999,
        //  description:"demo",
        //  star:5,
        //  imgCount:6,
        // img:"/img/prod/Samsung om 75s(31)esgn (1).jpeg",
        // },
        // {name:"Samsung",
        //  price:999,
        //  description:"demo",
        //  star:5,
        //  imgCount:6,
        // img:"/img/prod/Samsung om 75s(31)esgn (1).jpeg",
        // },

]

export {productsData}


        // {name:"Samsung",
        //  price:999,
        //  description:"demo",
        //  star:5,
        //  imgCount:6,
        // img:"/img/prod/Samsung om 75s(31)esgn (1).jpeg",
        // },